name: Unit Test

on:
  workflow_dispatch:
  pull_request:
      branches:
      - '*'
      - '!gh-pages'   # excludes gh-pages

jobs:
  unit-test-run:
    name: Testing Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install a project with a clean slate
        run: |
          npm ci

      - name: Unit Test   # 유닛 테스트 진행
        run: npm run test:unit
